<?php

namespace intakeBundle\Repository;

/**
 * appointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class appointmentRepository extends \Doctrine\ORM\EntityRepository
{
}
